---
output_dir: output
data_sources:
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "roytomeij@hosting1:html"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']

# domain to which this site is deployed
base_url: http://roytomeij.com

google_analytics:
  site_id: UA-7045996-4

# currently used by logo
site_name: "Roy Tomeij"

# default description
site_description: "Personal homepage of Roy Tomeij, entreprenerd."

# number of full featured posts to display on front
featured_count: 0

# number of excerpted posts to display on front
excerpt_count: 6

# number of other articles to reference at bottom of each article
other_articles_max: 1

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: roytomeij

